# Relation types
PARENT = 'PARENT_CLASS_OF'

# Node types
OFF_TECH = 'OFFENSIVE_TECHNIQUE'
DEF_TECH = 'DEFENSIVE_TECHNIQUE'
DEF_TAC = 'DEFENSIVE_TACTIC'
OFF_TAC = 'OFFENSIVE_TACTIC'
ARTIFACT = 'ARTIFACT'
SOFTWARE = 'SOFTWARE'
GROUP = 'THREAT_GROUP'
CAMPAIGN = 'CAMPAIGN'